"""audio table

Revision ID: d9ff552729bf
Revises: a2bf63b8bfaf
Create Date: 2023-03-30 15:32:27.251716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ff552729bf'
down_revision = 'a2bf63b8bfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audioname', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_audioname'), ['audioname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_audioname'))

    op.drop_table('audio')
    # ### end Alembic commands ###
